"""empty message

Revision ID: 1010232084b9
Revises: 590ab81589e8
Create Date: 2018-09-11 22:58:30.587070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1010232084b9'
down_revision = '590ab81589e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prevue', sa.Column('pre_movie_url', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prevue', 'pre_movie_url')
    # ### end Alembic commands ###
