"""empty message

Revision ID: 590ab81589e8
Revises: a156633c8d09
Create Date: 2018-09-07 16:09:26.249097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '590ab81589e8'
down_revision = 'a156633c8d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_time',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_time',
               existing_type=sa.String(length=50),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
