"""empty message

Revision ID: a156633c8d09
Revises: 
Create Date: 2018-09-07 12:01:13.963689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a156633c8d09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('labels', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movies', 'labels', ['labels'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_column('movies', 'labels')
    # ### end Alembic commands ###
